#!/usr/bin/env python3
"""One-time scraper: archives the Adobe Portfolio site kurdiani.ge into content/.

Produces, per project:
  content/projects/<slug>/project.md   - title / year / order / layout / description
  content/projects/<slug>/cover.jpg    - pre-cropped cover rendition (from Adobe)
  content/projects/<slug>/images/NN.*  - project images (largest variant <= 1920px)
  content/projects/<slug>/videos/NN.mp4- videos from Adobe CCV embeds

layout tokens (document order): grid:a-b | full:n | video:n
Defaults to one grid of all images when omitted.

Kept in the repo for reference; the live site is generated by build.py from content/.
"""
import html
import json
import os
import re
import subprocess
import sys
import urllib.request

BASE = "https://kurdiani.ge"
ROOT = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.join(ROOT, "content", "projects")
TAG_RE = re.compile(r"<[^>]+>")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req) as r:
        return r.read().decode("utf-8", "replace")


def parse_srcset(srcset):
    out = []
    for part in (srcset or "").split(","):
        m = re.match(r"\s*(\S+)\s+(\d+)w", part)
        if m:
            out.append((int(m.group(2)), m.group(1)))
    return out


def best_variant(srcset, data_src, cap=1920):
    entries = parse_srcset(srcset)
    if not entries:
        return data_src
    under = [e for e in entries if e[0] <= cap]
    return max(under)[1] if under else min(entries)[1]


def parse_home(html_text):
    projects = []
    for m in re.finditer(
        r'<a class="project-cover[^"]*" href="/([^"]+)".*?'
        r'data-src="([^"]+)"\s+data-srcset="([^"]*)".*?'
        r'<div class="title preserve-whitespace">(.*?)</div>\s*'
        r'(?:<div class="date">(.*?)</div>)?',
        html_text,
        re.S,
    ):
        slug, data_src, srcset, title, year = m.groups()
        projects.append(
            {
                "slug": slug,
                "title": html.unescape(title).strip(),
                "year": html.unescape(year or "").strip(),
                "cover_url": best_variant(srcset, data_src, cap=1280),
            }
        )
    return projects


def rich_text_to_lines(block_html):
    block_html = re.sub(r"<br\s*/?>", "\n", block_html)
    block_html = re.sub(r"</div>|</p>", "\n", block_html)
    lines = [html.unescape(l).rstrip() for l in TAG_RE.sub("", block_html).split("\n")]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    return lines


GRID_IMG_RE = re.compile(
    r'<img\s+class="grid__item-image[^"]*"[^>]*?data-src="([^"]+)"\s+data-srcset="([^"]*)"', re.S
)
FULL_IMG_RE = re.compile(
    r'<img\s+class="js-lazy e2e-site-project-module-image"[^>]*?data-src="([^"]+)"\s+data-srcset="([^"]*)"', re.S
)
CCV_RE = re.compile(r'src="(https://www-ccv\.adobe\.io/v1/player/ccv/([^/"]+)/embed[^"]*)"')


def parse_project(page_html):
    """Return {title, description, texts, modules:[(kind, payload)...]}.

    kinds: grid -> [img_url,...]; full -> img_url; video -> ccv embed url
    """
    title = ""
    m = re.search(r'<h1 class="title[^"]*">(.*?)</h1>', page_html, re.S)
    if m:
        title = html.unescape(m.group(1)).strip()
    desc = ""
    m = re.search(r'<p class="description">(.*?)</p>', page_html, re.S)
    if m:
        desc = html.unescape(TAG_RE.sub("", m.group(1))).strip()

    # split document into top-level module chunks in order
    modules = []
    texts = []
    starts = [
        (m.start(), m.group(1))
        for m in re.finditer(r'<div class="project-module module ([\w-]+)', page_html)
    ]
    for i, (pos, kind) in enumerate(starts):
        end = starts[i + 1][0] if i + 1 < len(starts) else len(page_html)
        chunk = page_html[pos:end]
        if kind == "media_collection":
            imgs = [best_variant(s, d) for d, s in GRID_IMG_RE.findall(chunk)]
            if imgs:
                # tree modules nest media_collections; nested ones appear as their
                # own starts entries, so chunks stay non-overlapping
                if modules and modules[-1][0] == "grid":
                    modules[-1][1].extend(imgs)
                else:
                    modules.append(["grid", imgs])
        elif kind == "image":
            for d, s in FULL_IMG_RE.findall(chunk):
                modules.append(["full", best_variant(s, d)])
        elif kind == "video":
            vm = CCV_RE.search(chunk)
            if vm:
                modules.append(["video", vm.group(1)])
        elif kind == "text":
            tm = re.search(r'<div class="rich-text[^"]*"[^>]*>(.*)', chunk, re.S)
            if tm:
                lines = rich_text_to_lines(tm.group(1))
                if lines:
                    texts.append("\n".join(lines))
        elif kind == "tree":
            pass  # container only; nested collections handled above
        else:
            modules.append(["unknown:" + kind, None])
    return {"title": title, "description": desc, "texts": texts, "modules": modules}


def ccv_mp4_url(embed_url):
    """Resolve an Adobe CCV embed to its best signed mp4 rendition URL."""
    page = fetch(embed_url.replace("&amp;", "&"))
    mp4s = re.findall(r'https://cdn-prod-ccv\.adobe\.com/[^"\' ]+_(\d+)\.mp4\?[^"\' ]+', page)
    urls = re.findall(r'(https://cdn-prod-ccv\.adobe\.com/[^"\' ]+_\d+\.mp4\?[^"\' ]+)', page)
    if not urls:
        return None
    best = max(zip((int(r) for r in mp4s), urls))
    return html.unescape(best[1])


def main():
    os.makedirs(CONTENT, exist_ok=True)
    home = fetch(BASE + "/")
    projects = parse_home(home)
    print(f"home grid: {len(projects)} projects")

    downloads = []
    report = []
    for order, p in enumerate(projects, start=1):
        slug = p["slug"]
        info = parse_project(fetch(f"{BASE}/{slug}"))
        pdir = os.path.join(CONTENT, slug)
        imgdir = os.path.join(pdir, "images")
        os.makedirs(imgdir, exist_ok=True)

        layout_tokens = []
        img_n = 0
        vid_n = 0
        unknown = []
        for kind, payload in info["modules"]:
            if kind == "grid":
                first = img_n + 1
                for url in payload:
                    img_n += 1
                    ext = os.path.splitext(url.split("?")[0])[1].lower() or ".jpg"
                    downloads.append((url, os.path.join(imgdir, f"{img_n:02d}{ext}")))
                layout_tokens.append(f"grid:{first}-{img_n}")
            elif kind == "full":
                img_n += 1
                ext = os.path.splitext(payload.split("?")[0])[1].lower() or ".jpg"
                downloads.append((payload, os.path.join(imgdir, f"{img_n:02d}{ext}")))
                layout_tokens.append(f"full:{img_n}")
            elif kind == "video":
                mp4 = ccv_mp4_url(payload)
                if mp4:
                    vid_n += 1
                    vdir = os.path.join(pdir, "videos")
                    os.makedirs(vdir, exist_ok=True)
                    downloads.append((mp4, os.path.join(vdir, f"{vid_n:02d}.mp4")))
                    layout_tokens.append(f"video:{vid_n}")
                else:
                    unknown.append("video-unresolved")
            else:
                unknown.append(kind)
        downloads.append((p["cover_url"], os.path.join(pdir, "cover.jpg")))

        default_layout = [f"grid:1-{img_n}"] if img_n else []
        body = info["description"]
        if info["texts"]:
            body = (body + "\n\n" if body else "") + "\n\n".join(info["texts"])
        with open(os.path.join(pdir, "project.md"), "w") as f:
            f.write("---\n")
            f.write(f"title: {info['title'] or p['title']}\n")
            if p["year"]:
                f.write(f"year: {p['year']}\n")
            f.write(f"order: {order}\n")
            if layout_tokens != default_layout:
                f.write(f"layout: {' '.join(layout_tokens)}\n")
            f.write("---\n")
            if body:
                f.write(body + "\n")

        report.append({"slug": slug, "title": info["title"] or p["title"], "year": p["year"],
                       "images": img_n, "videos": vid_n, "layout": layout_tokens,
                       "unknown": unknown})
        print(f"[{order:02d}] {slug}: {img_n} images, {vid_n} videos"
              + (f", UNKNOWN {unknown}" if unknown else ""))

    with open(os.path.join(ROOT, "content", ".scrape-report.json"), "w") as f:
        json.dump(report, f, indent=2)

    todo = [(u, d) for u, d in downloads
            if not (os.path.exists(d) and os.path.getsize(d) > 1000)]
    print(f"\n{len(downloads)} files total, {len(todo)} to download...")
    if todo:
        proc = subprocess.run(
            ["xargs", "-P", "10", "-n", "2", "curl", "-sS", "--fail", "--retry", "3", "-o"],
            input="".join(f"{dest} {url}\n" for url, dest in todo),
            text=True, capture_output=True,
        )
        if proc.returncode != 0:
            print("curl stderr:", proc.stderr[-2000:])

    missing = [d for _, d in downloads if not os.path.exists(d) or os.path.getsize(d) < 1000]
    print(f"present: {len(downloads) - len(missing)}, missing/small: {len(missing)}")
    for d in missing[:20]:
        print("  MISSING:", d)
    sys.exit(1 if missing else 0)


if __name__ == "__main__":
    main()
